defaults: &defaults
  timeout_in_minutes: 60
  agents:
    queue: "ci-non-gpu-basic"

steps:
  - <<: *defaults
    name: ":golang:"
    command: ".buildkite/steps/tests.sh"
    plugins:
      - docker#v3.1.0:
          image: "golang:1.15"
          propagate-uid-gid: true

  - wait
  - <<: *defaults
    name: ":lambda:"
    command: ".buildkite/steps/build-lambda.sh"
    artifact_paths:
      - handler.zip

  - wait
  - <<: *defaults
    label: ":s3:"
    command: ".buildkite/steps/upload-to-s3.sh"
    agents:
      queue: "ci-admin"

  - wait
  - name: ":pipeline:"
    command: .buildkite/steps/upload-release-steps.sh
    branches: master


