defaults: &defaults
  timeout_in_minutes: 60
  agents:
    queue: "ci-non-gpu-basic"

steps:
  - <<: *defaults
    name: ":golang:"
    command: ".buildkite/steps/tests.sh"
    plugins:
      - docker#v3.1.0:
          image: "golang:1.15"
          workdir: /go/src/github.com/buildkite/buildkite-agent-scaler
          propagate-uid-gid: true
          user: buildkite-agent

  - wait
  - <<: *defaults
    name: ":lambda:"
    command: ".buildkite/steps/build-lambda.sh"
    plugins:
      - docker#v3.1.0:
          image: "golang:1.15"
          workdir: /go/src/github.com/buildkite/buildkite-agent-scaler
          volumes:
            - "go-module-cache:/go/pkg/mod"
            - "$(CURDIR):/go/src/github.com/buildkite/buildkite-agent-scaler"
          propagate-uid-gid: true
    artifact_paths:
      - handler.zip

  - wait
  - <<: *defaults
    label: ":s3:"
    command: ".buildkite/steps/upload-to-s3.sh"
    agents:
      queue: "ci-admin"

  - wait
  - name: ":pipeline:"
    command: .buildkite/steps/upload-release-steps.sh
    branches: master


